// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * L'issue de lecture telle qu'elle traverse l'IPC.
 *
 * Distincte de `LoadOutcome` : le front n'a pas besoin du chemin de quarantaine pour
 * décider quoi afficher, et lui envoyer un chemin absolu du disque de l'utilisateur
 * n'apporterait rien. Il a besoin de savoir **s'il peut écrire**.
 */
export type ConfigLoad = { "kind": "fresh" } | { "kind": "loaded", projects: Array<Project>, } | { "kind": "unreadable", reason: string, 
/**
 * Où l'original a été mis de côté, à montrer pour qu'il soit récupérable.
 */
quarantinedTo: string, } | { "kind": "tooNew", found: number, supported: number, };

/**
 * Ce que `A2` envoie pour créer un projet.
 */
export type CreateProjectRequest = { name: string, 
/**
 * L'environnement actif du projet, qui est celui de la variante qu'on lui déclare.
 *
 * `05a` en fait une propriété du **projet**, et `A2` ne propose que celui de la variante. Le
 * coder à `dev` afficherait un arbre vide juste après l'enregistrement d'une base `prod` : la
 * base existe, mais dans un autre environnement que celui affiché.
 */
activeEnvironment: Environment, };

/**
 * Une base d'un projet, déclinée en 1..n environnements.
 */
export type Database = { name: string, engine: Engine, variants: Array<EnvironmentVariant>, };

/**
 * Les sept moteurs du handoff, et rien d'autre : un moteur inconnu ne compile pas.
 */
export type Engine = "postgresql" | "mysql" | "sqlite" | "mongodb" | "redis" | "snowflake" | "bigquery";

/**
 * Les trois environnements du handoff. L'environnement actif est une propriété du
 * **projet**, pas de la base — c'est ce qui permet à un basculement de recharger
 * l'arbre entier sur d'autres serveurs sans changer l'arborescence.
 */
export type Environment = "dev" | "staging" | "prod";

/**
 * Les réglages de connexion d'une base **pour un environnement donné**. Le handoff pose
 * « host/port/creds différents par env », donc tout le formulaire de `A2` vit ici, à
 * l'exception du nom et du moteur qui appartiennent à la base.
 */
export type EnvironmentVariant = { environment: Environment, host: string, port: number, defaultDatabase: string, username: string, 
/**
 * Référence vers le mot de passe, jamais le mot de passe. `None` pour un moteur
 * qui n'en demande pas — SQLite sur fichier, par exemple.
 */
password: SecretRef | null, sslMode: SslMode, 
/**
 * Réglage **saisi** dans `A2`. L'état effectif d'une base ouverte compose ce
 * réglage, la préférence globale de `A10` et l'environnement courant : c'est une
 * règle, pas une donnée, et elle appartient à `11`. Voir `specs/05a`.
 */
readOnly: boolean, reconnectOnStartup: boolean, tunnel: Tunnel | null, };

/**
 * Un projet : ce que la sidebar liste. Pas des connexions — le handoff insiste.
 */
export type Project = { name: string, 
/**
 * Global au projet, et persisté (`05b`) : le handoff le traite comme une propriété
 * du projet, pas comme une préférence d'affichage.
 */
activeEnvironment: Environment, databases: Array<Database>, };

/**
 * Ce que `A2` envoie en cliquant « Enregistrer & ouvrir ».
 *
 * Le mot de passe est **en clair et séparé**, comme dans `ConnectionRequest` de `08d` : aucune
 * `SecretRef` n'existe avant que le secret soit rangé, et c'est justement le travail de cette
 * commande. La variante reçue porte donc `password: null`, que `enregistrer` remplace.
 */
export type SaveDatabaseRequest = { project: string, database: string, engine: Engine, variant: EnvironmentVariant, password: string | null, };

/**
 * Le mécanisme réellement employé, tel que le front l'apprend.
 *
 * Le badge vert « Trousseau » de `A2` serait un mensonge en développement : l'écran doit
 * pouvoir dire la vérité, donc il a besoin de cette information.
 */
export type SecretMechanism = "keychain" | "encryptedFile";

/**
 * Référence vers un secret rangé par `05c` — **jamais sa valeur**.
 *
 * Type distinct plutôt qu'un alias de `String` : une valeur de secret ne peut pas y
 * être affectée par erreur, puisqu'aucune conversion implicite n'existe. Rien à
 * divulguer ici de toute façon, une référence n'est pas un secret.
 */
export type SecretRef = string & { readonly __secretRef: unique symbol };

export type SslMode = "disable" | "allow" | "prefer" | "require" | "verify-ca" | "verify-full";

/**
 * Proxy / tunnel du panneau de `A2`. Le **chemin** de la clé privée est de la
 * configuration, pas un secret — voir `specs/05c` § Hors périmètre.
 */
export type Tunnel = { kind: TunnelKind, bastionHost: string, bastionPort: number, username: string, privateKeyPath: string, 
/**
 * `None` signifie « auto » — le port local est choisi à l'ouverture par `06`.
 */
localPort: number | null, };

export type TunnelKind = "ssh";
