// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Ce que la barre d'état affiche quand une version plus récente existe.
 *
 * **La version courante n'y est pas** : le front la connaît déjà (`__APP_VERSION__`), et la
 * rendre ici installerait deux vérités pour une seule valeur — dont la visible pourrait être
 * la fausse le jour où le binaire et le bundle divergent.
 */
export type AvailableUpdate = { version: string, 
/**
 * Les notes de la release GitHub, telles que le manifeste les porte. `None` quand la
 * release n'en a pas — l'écran doit tenir sans, et le dit.
 */
notes: string | null, };
